### ISSUE TITLE
[FEATURE REQUEST] Add the ability to document versioned endpoints

### ISSUE THREAD

**Issue by po-trottier** [community-of-python/fast-version#1]
At the moment versioned endpoints are ignored in the OpenAPI documentation. 

It would be nice if there was a way to see versioned endpoints in there with the header automatically applied.

The 2nd entry would have the same URL but a different header value and would build based off the 2nd function definition so it would be able to have a different description, return model, etc.

![image](https://github.com/modern-python/fast-version/assets/41876093/91e07072-9757-4ac7-b5cd-4fdabed21190)

![image](https://github.com/modern-python/fast-version/assets/41876093/9de3d5e3-b50e-4075-8989-d4e308439c90)

**Comment by lesnik512** [comment]
Actually, versions are not ignored in open api. There are select boxes with different payload versions for request and response:

<img width="500" alt="310224901-3bdaee89-50f4-4861-a7d2-f6eb7fe32211" src="https://github.com/modern-python/fast-version/assets/2184855/f2d72e8f-f601-4912-a530-9560344e2f5e">

<img width="1432" alt="310224890-2b2fa083-e512-4d75-84fa-a700a33fe912" src="https://github.com/modern-python/fast-version/assets/2184855/cee6acc4-a999-4e1b-a931-585e7b0e9d9a">

P.S. I will add info about this in README

**Comment by po-trottier** [comment]
That's good to know, however, that would only update the response model documentation,right? 

What if the endpoint's body content changed between v1 and v2 or the query parameters changed? Then you would only see the values for v1, correct?

**Comment by lesnik512** [comment]
For different body content openapi provides several schemas based on media type (means different version) and selectbox is present to choose.

I checked for get params and looks like there is no way to choose different set of get params for different media types (means different version)

And OpenAPI do not support paths with the same path and request type. It can be achieved with duplicating paths with added invisible chars, but it looks quite ugly for my taste
