### ISSUE TITLE
[FEATURE REQUEST] Add the ability to change the "default version" behavior

### ISSUE THREAD

**Issue by po-trottier** [community-of-python/fast-version#2]
It would be nice if when initializing the library (`init_fastapi_versioning`) we could set the default version behavior.

Something like:
- First (select v1)
- Last (select the highest version, say v2)
- Explicit (raise an HTTP Error when a version is not explicitly specific in the request)

**Comment by lesnik512** [comment]
Hi and thanks for proposals:)
